# NumPy Assignment

This assignment will help you practice working with NumPy arrays, including normalization, finding closest values, sorting, and array manipulation.

Make sure to import NumPy before starting!

In [2]:
import numpy as np

## Problem 1: Array Normalization

Create a 3x3 array with random integers between 1 and 100. Write a program to "normalize" the array so that the values are scaled between 0 and 1.

**Formula:** `(x - min) / (max - min)`

**Example Output:** An array where the smallest value becomes 0.0 and the largest becomes 1.0.

In [24]:
array = np.random.randint(low=1, high=101, size=(3, 3))
print("Array:\n", array)
min_value = array.min()
max_value = array.max()

normalized = (array - min_value) / (max_value - min_value)
print("Normalized Array:\n", normalized)

Array:
 [[81  8 35]
 [35 33  5]
 [41 28  7]]
Normalized Array:
 [[1.         0.03947368 0.39473684]
 [0.39473684 0.36842105 0.        ]
 [0.47368421 0.30263158 0.02631579]]


## Problem 2: Find Closest Value

Create a 1D array of 10 random numbers. Ask the user for a value X. Find the value in the array that is closest to X.

**Example Input:**
- Array: `[1, 5, 8, 12]`
- X = 10

**Example Output:** 8 or 12 (whichever is mathematically closer)

In [87]:
array = np.random.randint(30, size=10)
x = 10
print("Array:\n", array)

closest = array[np.abs(array - x).argmin()]
print("Closest value to", x, "is", closest)

Array:
 [ 6 27 13 19 18 25 14 15 20  4]
Closest value to 10 is 13


## Problem 3: Second-Largest Value in Each Column

Write a NumPy program to create a 5x5 array with random values. For each column in the array, find the second-largest value.

**Example Input:**
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

**Example Output:** `[4, 5, 6]` (These are the second-highest values for each respective column)

In [22]:
array = np.random.randint(low=1, high=101, size=(5, 5))
print("Array:\n", array)


second_highest = np.array([
  np.unique(array[:, col])[-2]
  for col in range(array.shape[1])
])

print("Second highest values in each column:\n", second_highest)

Array:
 [[ 73  83  77  40  25]
 [ 30  61  44  29  53]
 [ 87  85  61   7 100]
 [ 64  76  35  93  29]
 [ 18  17   2  46  95]]
Second highest values in each column:
 [73 83 61 46 95]


## Problem 4: Find Rows with Even Sum

Create a 6x4 matrix of random integers. Identify which rows have a sum that is an even number. Print the indices of these rows.

In [61]:
array = np.random.randint(low=1, high=101, size=(6, 4))
print("Array:\n", array)

row_sums = array.sum(axis=1)
print("Sum of each row:\n", array.sum(axis=1))

even_rows_indices = np.where(row_sums % 2 == 0)[0]
print("Indices of rows with even sums:\n", even_rows_indices)

Array:
 [[ 21  17  13  10]
 [ 65  42  61   2]
 [ 59  33   3  64]
 [ 75  15  52   3]
 [ 50  17  59  54]
 [ 64  28  68 100]]
Sum of each row:
 [ 61 170 159 145 180 260]
Indices of rows with even sums:
 [1 4 5]


## Problem 5: Replace Multiples

Create a 1D array of 30 random integers between 1 and 50. Replace all numbers that are multiples of 3 or 5 with the value -1.

**Example Input:** `[3, 7, 10, 15]`

**Example Output:** `[-1, 7, -1, -1]`

In [71]:
array = np.random.randint(low=1, high=51, size=(1, 30))

print("Array:\n", array)

array[(array % 3 == 0) | (array % 5 == 0)] = -1
print("Array with multiples of 3 or 5 replaced by -1:\n", array)

Array:
 [[25 50 25 27 15  5 23 24 13 46 45 22 30  1 14 35  5 46 31  4 36 33 24 43
  20 23 28 10 39 32]]
Array with multiples of 3 or 5 replaced by -1:
 [[-1 -1 -1 -1 -1 -1 23 -1 13 46 -1 22 -1  1 14 -1 -1 46 31  4 -1 -1 -1 43
  -1 23 28 -1 -1 32]]


## Problem 6: Row Mean Subtraction

Write a NumPy program to create a 3x3 array with random values. For each row, calculate its mean (average) and subtract that mean from every element in that specific row.

**Example Input:**
```
[[10, 20, 30],
 [5, 5, 5],
 [0, 10, 20]]
```

**Example Output:**
```
[[-10.  0. 10.],
 [ 0.  0.  0.],
 [-10.  0. 10.]]
```

In [90]:
array = np.random.randint(low=1, high=101, size=(3, 3))
print("Array:\n", array)

row_means = array.mean(axis=1, keepdims=True)
print("Mean of each row:\n", row_means)

result = array - row_means
print("Array after subtracting row means:\n", result)


Array:
 [[54  1  5]
 [67 87 34]
 [52 76 93]]
Mean of each row:
 [[20.        ]
 [62.66666667]
 [73.66666667]]
Array after subtracting row means:
 [[ 34.         -19.         -15.        ]
 [  4.33333333  24.33333333 -28.66666667]
 [-21.66666667   2.33333333  19.33333333]]
